### ISSUE TITLE
How to add new meetings

### ISSUE THREAD

**Issue by Cogitri** [plibither8/ulauncher-zoom#1]
Hej,

I'm not quite sure how one can add new meetings to the extension. From reading the code I suppose adding a meeting manually to the meetings.json should work but seems like that doesn't quite cut it:

```
[{"meeting_id":123, "password": "pwd", "name": "Meeting"}]
```

**Comment by luongson86** [comment]
> Hej,
> 
> I'm not quite sure how one can add new meetings to the extension. From reading the code I suppose adding a meeting manually to the meetings.json should work but seems like that doesn't quite cut it:
> 
> ```
> [{"meeting_id":123, "password": "pwd", "name": "Meeting"}]
> ```

from your suggestion i did it, just a little tweak:
```
[
  {
    "id": "meeting_id",
    "pwd": "hash_password",
    "name": "meeting_name"
  }
]
```

you can get infomation in zoomURL like:
```
https://zoom.us/j/1234554321?pwd=ThisIsHashPassword
```

**Comment by plibither8** [comment]
@Cogitri apologies for the delay in responding, and @luongson86 thanks for the response!

I should've added these instruction way before, sorry for that. I've updated the README, you can find the instructions there :)
