### ISSUE TITLE
Feat: handling events without touching json

### ISSUE THREAD

**Issue by marabesi** [plibither8/ulauncher-zoom#3]
Hello there! 

First of all, thanks for this ext, I started to use it and so far I am enjoying. I am opening this issue to ask and also discuss if would be possible to implement a better way of handling meetings as opposed to json.

For example, the [google meet extension](https://ext.ulauncher.io/-/github-randomcharacter-ulauncher-meet) uses a ; approach to store the meet info. This becomes handy as you can story the meetings without leaving ulauncher.

![image](https://user-images.githubusercontent.com/2129872/148185991-779006a1-2589-4fb6-aad4-970b68c3e99b.png)

**Comment by Dankni95** [comment]
This should be totally possible, i dont know how active @plibither8 is, but he noted on issue #2 that he has little time.

I will try to work this out and make a pull request :smile: 

EDIT:
A questions as i dont use zoom as much:
Do you store the name, id and password for later use or is it just to connect once?

As far as i understand the meeting ID changes for every zoom session, why do we need saved meetings?

**Comment by marabesi** [comment]
I think you correct about switch meeting ids for no scheduled ones, but for example, on my daily basis I use a fixed room - thus the id remains the same.

For the password, as I am already logged in, zoom just picks my account and logs me in into the meeting - this is a good point, as I haven't thought about this scenario. Anyways, I think a good start wold be to create a pattern like the one in the meet, given the json:

```json
  {
    "name": "Personal Meeting",
    "id": "1234567890",
    "pwd": "ABC123"
  },
````

I will then configure the extension like:

```
Personal Meeting:1234567890:ABC123
```

To be honest, I don't know if : is suitable for splitting the info.

**Comment by Dankni95** [comment]
Hi again, thanks for the answer!

Please try these changes i made and tell me what you think or if it even works :laughing: 

keyword is `mz join` should be straight forward next, there is no json file, everything is done in ulauncher prompt.

https://github.com/Dankni95/ulauncher-zoom

Daniel

**Comment by marabesi** [comment]
hjey @Dankni95 thanks for that, it works like a charm - one question though, is it possible to clean up the meetings history once they are recorded?

**Comment by Dankni95** [comment]
> hjey @Dankni95 thanks for that, it works like a charm - one question though, is it possible to clean up the meetings history once they are recorded?

Hi, awesome, i have not implemented anything in the ulauncher that deletes the history as of right now. You can easily delete history if you cd into `~/.local/share/ulauncher/extensions/com.github.dankni95.ulauncher-zoom` and pick history to delete in `meetings` file. Delete the whole line.

I can implement delete feature later :smile:

**Comment by marabesi** [comment]
@Dankni95 no worries, thanks for the help on this one. Will close the issue as I consider it solved.

Thanks again!
